using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class MakeMapObject : MonoBehaviour
{
    //this script should be added to the objects that we need to display on mini-map
    [SerializeField]
    public Image image; //choose the image that we want to hook up the object

	// Use this for initialization
	void Start ()
	{
        //At the start, register the object and it's image to the object list that will be rendered
        MiniMapController.RegisterMapObject(gameObject, image);
    }
	
	// Update is called once per frame
	void OnDestroy ()
	{
        //if the object is destroyed, Remove the object from the list
        //ex: items the generated by the spawners
        MiniMapController.RemoveMapObject(gameObject);
    }
}
